import 'package:sarqyt/src/features/offers/domain/offer.dart';

final kTestOffers = [
  Offer(
    id: '1',
    imageUrl: 'assets/products/cheeseburger.jpg',
    title: 'Cheesburger',
    description: 'Lorem ipsum',
    origPrice: 23,
    currPrice: 15,
    availableQuantity: 5,
    avgRating: 4.5,
    storeId: '1',
    storeName: 'Burger House',
    storeImage: 'assets/stores/burger_house.jpg',
    expiresAt: DateTime.now().add(const Duration(days: 3)),
    category: Category.fastfood,
  ),
  Offer(
    id: '2',
    imageUrl: 'assets/products/chicken-burger.jpg',
    title: 'Chicken burger',
    description: 'Lorem ipsum',
    origPrice: null,
    currPrice: 14,
    availableQuantity: 5,
    avgRating: 4.5,
    storeId: '1',
    storeName: 'Burger House',
    storeImage: 'assets/stores/burger_house.jpg',
    expiresAt: DateTime.now().add(const Duration(days: 3)),
    category: Category.fastfood,
  ),
  Offer(
    id: '3',
    imageUrl: 'assets/products/double-burger.webp',
    title: 'Double burger',
    description: 'Lorem ipsum',
    origPrice: null,
    currPrice: 20,
    availableQuantity: 5,
    avgRating: 4.5,
    storeId: '1',
    storeName: 'Burger House',
    storeImage: 'assets/stores/burger_house.jpg',
    expiresAt: DateTime.now().add(const Duration(days: 3)),
    category: Category.fastfood,
  ),
  Offer(
    id: '4',
    imageUrl: 'assets/products/fried-leg.jpeg',
    title: 'Fried leg',
    description: 'Lorem ipsum',
    origPrice: 8,
    currPrice: 5,
    availableQuantity: 5,
    avgRating: 4.5,
    storeId: '2',
    storeName: 'KFC Copy',
    storeImage: 'assets/stores/kfc_copy.jpg',
    expiresAt: DateTime.now().add(const Duration(days: 3)),
    category: Category.hotDish,
  ),
  Offer(
    id: '5',
    imageUrl: 'assets/products/fried-wings.webp',
    title: 'Fried wings',
    description: 'Lorem ipsum',
    origPrice: null,
    currPrice: 6,
    availableQuantity: 5,
    avgRating: 4.5,
    storeId: '2',
    storeName: 'KFC Copy',
    storeImage: 'assets/stores/kfc_copy.jpg',
    expiresAt: DateTime.now().add(const Duration(days: 3)),
    category: Category.hotDish,
  ),
  Offer(
    id: '6',
    imageUrl: 'assets/products/chocolate-cake.jpg',
    title: 'Chocolate cake',
    description: 'Lorem ipsum',
    origPrice: null,
    currPrice: 15,
    availableQuantity: 10,
    avgRating: 4.5,
    storeId: '3',
    storeImage: 'assets/stores/sweet_tooth.jpg',
    storeName: 'Sweet Tooth',
    expiresAt: DateTime.now().add(const Duration(days: 3)),
    category: Category.desert,
  ),
  Offer(
    id: '7',
    description: 'Lorem ipsum',
    imageUrl: 'assets/products/cherry-cake.jpg',
    title: 'Cherry cake',
    origPrice: null,
    currPrice: 14,
    availableQuantity: 10,
    avgRating: 4.5,
    storeId: '3',
    storeName: 'Sweet Tooth',
    storeImage: 'assets/stores/sweet_tooth.jpg',
    expiresAt: DateTime.now().add(const Duration(days: 3)),
    category: Category.desert,
  ),
  Offer(
    id: '8',
    imageUrl: 'assets/products/hamburger.jpg',
    title: 'Hamburger',
    description: 'Lorem ipsum',
    origPrice: null,
    currPrice: 12,
    availableQuantity: 10,
    avgRating: 4.5,
    storeId: '1',
    storeName: 'Burger House',
    storeImage: 'assets/stores/burger_house.jpg',
    expiresAt: DateTime.now().add(const Duration(days: 3)),
    category: Category.fastfood,
  ),
  Offer(
    id: '9',
    imageUrl: 'assets/products/pizza-margarita.jpg',
    title: 'Pizza margarita',
    description: 'Lorem ipsum',
    origPrice: null,
    currPrice: 18,
    availableQuantity: 10,
    avgRating: 4.5,
    storeId: '4',
    storeName: 'Pizzalino',
    storeImage: 'assets/stores/pizzalino.jpg',
    expiresAt: DateTime.now().add(const Duration(days: 3)),
    category: Category.hotDish,
  ),
  Offer(
    id: '10',
    imageUrl: 'assets/products/pizza-pepperoni.jpg',
    title: 'Pizza pepperoni',
    description: 'Lorem ipsum',
    origPrice: null,
    currPrice: 19,
    availableQuantity: 10,
    avgRating: 4.5,
    storeId: '4',
    storeName: 'Pizzalino',
    storeImage: 'assets/stores/pizzalino.jpg',
    expiresAt: DateTime.now().add(const Duration(days: 3)),
    category: Category.hotDish,
  ),
  Offer(
    id: '11',
    imageUrl: 'assets/products/sushi-baked.jpg',
    title: 'Sushi baked',
    description: 'Lorem ipsum',
    origPrice: null,
    currPrice: 16,
    availableQuantity: 5,
    avgRating: 4.5,
    storeId: '5',
    storeName: 'Sushi Master',
    storeImage: 'assets/stores/sushi_master.jpg',
    expiresAt: DateTime.now().add(const Duration(days: 3)),
    category: Category.sushi,
  ),
  Offer(
    id: '12',
    imageUrl: 'assets/products/sushi-philapelphia.jpeg',
    title: 'Sushi philadelphia',
    description: 'Lorem ipsum',
    origPrice: null,
    currPrice: 15,
    availableQuantity: 5,
    avgRating: 4.5,
    storeId: '5',
    storeName: 'Sushi Master',
    storeImage: 'assets/stores/sushi_master.jpg',
    expiresAt: DateTime.now().add(const Duration(days: 3)),
    category: Category.sushi,
  ),
  Offer(
    id: '13',
    imageUrl: 'assets/products/sushi-tempura.jpg',
    title: 'Sushi tempura',
    description: 'Lorem ipsum',
    origPrice: null,
    currPrice: 14,
    availableQuantity: 5,
    avgRating: 4.5,
    storeId: '5',
    storeName: 'Sushi Master',
    storeImage: 'assets/stores/sushi_master.jpg',
    expiresAt: DateTime.now().add(const Duration(days: 3)),
    category: Category.sushi,
  ),
];
