// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiR1zTvxcU7JC3_KJIhU3N3mSjFS93spE',
    appId: '1:1072615959986:web:845a0a4381e8a2b188c8ab',
    messagingSenderId: '1072615959986',
    projectId: 'sarqyt-1ab95',
    authDomain: 'sarqyt-1ab95.firebaseapp.com',
    storageBucket: 'sarqyt-1ab95.firebasestorage.app',
    measurementId: 'G-R0YWR59YG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIYIPEO-hhHYcWlnEkP3dM1TqtMEuo1Ac',
    appId: '1:1072615959986:android:318d2efa603e412988c8ab',
    messagingSenderId: '1072615959986',
    projectId: 'sarqyt-1ab95',
    storageBucket: 'sarqyt-1ab95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmgn_UMYpLG82KkkS_Dcvzs5Gu2kLgHTo',
    appId: '1:1072615959986:ios:c061e01ea24d05b588c8ab',
    messagingSenderId: '1072615959986',
    projectId: 'sarqyt-1ab95',
    storageBucket: 'sarqyt-1ab95.firebasestorage.app',
    iosBundleId: 'com.example.sarqyt',
  );
}
